"use client";

import { useState, useRef } from 'react';
import { motion } from 'motion/react';
import { ChevronDown, Download, RefreshCw, Shield, Lock, Zap, RotateCcw, DollarSign, TrendingDown, Server, Database, Activity, CloudCog, Home, Folder, Sun, Moon, Copy, Maximize2, Terminal } from 'lucide-react';
import { useNavigate, useParams } from 'react-router';

const terraformCode = `# Generated by Velocis IaC Predictor
# Source: latest commit on main branch
# Region: ap-south-1

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "ap-south-1"
}

# Lambda Function - Authentication Service
resource "aws_lambda_function" "auth_service" {
  filename      = "auth_service.zip"
  function_name = "auth-service-prod"
  role          = aws_iam_role.lambda_exec.arn
  handler       = "index.handler"
  runtime       = "nodejs20.x"
  
  memory_size = 256
  timeout     = 30
  
  environment {
    variables = {
      NODE_ENV = "production"
      DB_HOST  = aws_db_instance.main.endpoint
    }
  }
  
  # Velocis: New Lambda increases cold start surface
  tags = {
    ManagedBy = "Velocis"
    Service   = "Authentication"
  }
}

# API Gateway
resource "aws_apigatewayv2_api" "main" {
  name          = "velocis-api-prod"
  protocol_type = "HTTP"
  
  cors_configuration {
    allow_origins = ["*"]
    allow_methods = ["GET", "POST", "PUT", "DELETE"]
  }
}

# DynamoDB Table
resource "aws_dynamodb_table" "sessions" {
  name           = "user-sessions-prod"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "userId"
  range_key      = "sessionId"
  
  attribute {
    name = "userId"
    type = "S"
  }
  
  attribute {
    name = "sessionId"
    type = "S"
  }
  
  ttl {
    attribute_name = "expiresAt"
    enabled        = true
  }
  
  tags = {
    ManagedBy = "Velocis"
  }
}

# IAM Role for Lambda
resource "aws_iam_role" "lambda_exec" {
  name = "lambda-execution-role"
  
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

# Step Functions State Machine
resource "aws_sfn_state_machine" "workflow" {
  name     = "auth-workflow-prod"
  role_arn = aws_iam_role.step_functions_exec.arn
  
  definition = jsonencode({
    Comment = "Authentication workflow"
    StartAt = "ValidateUser"
    States = {
      ValidateUser = {
        Type = "Task"
        Resource = aws_lambda_function.auth_service.arn
        End = true
      }
    }
  })
}`;

export function InfrastructurePage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const [environment, setEnvironment] = useState<'production' | 'staging' | 'preview'>('production');
  const [monthlyCost, setMonthlyCost] = useState(18.42);
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [isWhyInfraExpanded, setIsWhyInfraExpanded] = useState(false);

  const themeClass = isDarkMode ? 'dark' : '';

  const repoName = id === 'infrazero' ? 'InfraZero' :
    id === 'immersa' ? 'Immersa' :
      id === 'velocis-core' ? 'velocis-core' :
        id === 'ai-observatory' ? 'ai-observatory' :
          id === 'distributed-lab' ? 'distributed-lab' :
            'test-sandbox';

  const costBreakdown = [
    { service: 'Lambda', cost: 8.50, percentage: 46, color: '#3b82f6' },
    { service: 'API Gateway', cost: 4.20, percentage: 23, color: '#8b5cf6' },
    { service: 'DynamoDB', cost: 3.40, percentage: 18, color: '#10b981' },
    { service: 'Step Functions', cost: 1.82, percentage: 10, color: '#f59e0b' },
    { service: 'Misc', cost: 0.50, percentage: 3, color: '#6b7280' }
  ];

  return (
    <div className={`${themeClass} w-full h-full`}>
      <style>
        {`
          .custom-scrollbar::-webkit-scrollbar {
            width: 6px;
            height: 6px;
          }
          .custom-scrollbar::-webkit-scrollbar-track {
            background: transparent;
          }
          .custom-scrollbar::-webkit-scrollbar-thumb {
            background-color: rgba(156, 163, 175, 0.3);
            border-radius: 10px;
          }
          .custom-scrollbar::-webkit-scrollbar-thumb:hover {
            background-color: rgba(156, 163, 175, 0.5);
          }
          .dark .custom-scrollbar::-webkit-scrollbar-thumb {
            background-color: rgba(71, 85, 105, 0.5);
          }
          .dark .custom-scrollbar::-webkit-scrollbar-thumb:hover {
            background-color: rgba(71, 85, 105, 0.8);
          }
        `}
      </style>

      {/* ── App Shell: viewport-locked, no page scroll ── */}
      <div className="w-full h-screen flex flex-col overflow-hidden bg-zinc-50 dark:bg-[#010308] font-['Geist_Sans',_'Inter',_sans-serif] transition-colors duration-300 relative">

        {/* Dark Mode Radial & Noise Overlays */}
        {isDarkMode && (
          <>
            <div className="absolute inset-0 pointer-events-none z-0 bg-[radial-gradient(circle_at_50%_0%,_rgba(30,41,59,1)_0%,_rgba(15,23,42,1)_100%)] opacity-80 mix-blend-multiply" />
            <div className="absolute inset-0 pointer-events-none z-0 shadow-[inset_0_0_150px_rgba(0,0,0,0.8)]" />
            <div
              className="absolute inset-0 pointer-events-none z-0 opacity-[0.03]"
              style={{
                backgroundImage: `url("data:image/svg+xml;utf8,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`,
                mixBlendMode: 'overlay'
              }}
            />
          </>
        )}

        {/* ── Top Navigation ── full-width, crisp border ── */}
        <div className="flex-none z-50 w-full border-b border-gray-200 dark:border-slate-800/80 bg-white dark:bg-slate-900/60 backdrop-blur-xl transition-colors duration-300 relative">
          <div className="w-full px-5 h-[52px] flex items-center justify-between">
            {/* Left – Breadcrumb */}
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-md flex items-center justify-center bg-zinc-900 dark:bg-slate-800 border border-zinc-700 dark:border-slate-700">
                  <span className="text-white font-bold text-xs">V</span>
                </div>
                <span className="font-semibold text-zinc-900 dark:text-slate-100 text-sm hidden sm:block tracking-tight">Velocis</span>
              </div>

              <div className="flex items-center gap-2 text-[13px] text-zinc-500 dark:text-slate-400 font-medium">
                <button
                  onClick={() => navigate('/dashboard')}
                  className="flex items-center gap-1.5 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
                >
                  <Home className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Dashboard</span>
                </button>
                <span className="text-zinc-300 dark:text-slate-700">/</span>
                <button
                  onClick={() => navigate(`/repo/${id}`)}
                  className="flex items-center gap-1.5 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
                >
                  <Folder className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">{repoName}</span>
                </button>
                <span className="text-zinc-300 dark:text-slate-700">/</span>
                <span className="text-zinc-900 dark:text-slate-100 font-semibold">Infrastructure</span>
              </div>
            </div>

            {/* Center – Environment Selector */}
            <div className="hidden md:flex items-center p-0.5 rounded-md bg-zinc-100/80 dark:bg-slate-800/80 border border-zinc-200/50 dark:border-slate-700/50 shadow-inner transition-colors">
              {(['production', 'staging', 'preview'] as const).map((env) => (
                <button
                  key={env}
                  onClick={() => setEnvironment(env)}
                  className={`px-3 py-1 rounded text-[13px] font-semibold transition-all capitalize ${environment === env
                    ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-indigo-300 shadow-sm border border-zinc-200/50 dark:border-slate-600/50'
                    : 'text-zinc-500 dark:text-slate-400 hover:text-zinc-700 dark:hover:text-slate-200'
                    }`}
                >
                  {env}
                </button>
              ))}
            </div>

            {/* Right – Actions */}
            <div className="flex items-center gap-2">
              <button
                className="p-1.5 rounded-md hover:bg-zinc-100 dark:hover:bg-slate-800 transition-colors text-zinc-500 dark:text-slate-400 hover:text-zinc-900 dark:hover:text-slate-100 hidden sm:block"
                title="Refresh"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
              <button
                className="p-1.5 rounded-md hover:bg-zinc-100 dark:hover:bg-slate-800 transition-colors text-zinc-500 dark:text-slate-400 hover:text-zinc-900 dark:hover:text-slate-100 hidden sm:block"
                title="Export IaC"
              >
                <Download className="w-4 h-4" />
              </button>
              <button
                onClick={() => setIsDarkMode(!isDarkMode)}
                className="p-1.5 rounded-md hover:bg-zinc-100 dark:hover:bg-slate-800 transition-colors text-zinc-500 dark:text-slate-400 hover:text-zinc-900 dark:hover:text-slate-100"
              >
                {isDarkMode ? <Moon className="w-4 h-4" /> : <Sun className="w-4 h-4" />}
              </button>
              <div className="relative ml-1">
                <div className="w-7 h-7 rounded-full flex items-center justify-center bg-white dark:bg-slate-800 border border-indigo-100 dark:border-indigo-500/30 shadow-sm cursor-pointer hover:scale-105 transition-transform">
                  <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400">R</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ── Context Strip ── full-width info bar ── */}
        <div className="flex-none w-full border-b border-gray-200 dark:border-slate-800/80 bg-white/50 dark:bg-slate-900/40 backdrop-blur-md transition-colors duration-300 relative z-40">
          <div className="w-full px-5 py-2 flex items-center justify-between">
            <div className="flex flex-col justify-center">
              <div className="font-semibold text-[13px] text-zinc-900 dark:text-slate-100 transition-colors leading-tight">
                IaC Predictor active
              </div>
              <div className="text-[11px] text-zinc-500 dark:text-slate-400 transition-colors leading-tight mt-0.5">
                Infrastructure changes generated from latest commit
              </div>
            </div>

            <div className="flex items-center gap-4">
              <div className="inline-flex items-center px-2.5 h-[22px] rounded text-[10px] sm:text-[11px] font-bold uppercase tracking-wider bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 border border-indigo-100/50 dark:border-indigo-800/30 shadow-sm transition-colors leading-none">
                Generated by Velocis AI
              </div>
              <span className="inline-flex items-center h-[22px] text-[11px] font-medium text-zinc-500 dark:text-slate-400 transition-colors leading-none">
                Last updated 2 min ago
              </span>
              <span className="hidden sm:inline-flex items-center h-[22px] text-[11px] font-medium text-zinc-500 dark:text-slate-400 transition-colors leading-none">
                Region: ap-south-1
              </span>
            </div>
          </div>
        </div>

        {/* ══════════════════════════════════════════════════════════════
            MAIN CONTENT — structural split-pane, fills remaining height
            ══════════════════════════════════════════════════════════════ */}
        <div className="flex-1 flex flex-row overflow-hidden relative z-10">

          {/* ── LEFT PANE: Code Editor (70%) ── */}
          <motion.div
            initial={{ opacity: 0, x: -12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4 }}
            className="w-[70%] h-full bg-white dark:bg-[#010308]/50 border-r border-gray-200 dark:border-slate-800 flex flex-col relative transition-colors duration-300"
          >
            {/* Subtle glow */}
            <div className="absolute top-0 right-1/4 w-96 h-96 bg-indigo-50/50 dark:bg-indigo-900/10 rounded-full blur-[100px] pointer-events-none" />

            {/* Panel Header — sticky */}
            <div className="sticky top-0 z-20 flex flex-col bg-zinc-50/90 dark:bg-slate-900/80 backdrop-blur-md border-b border-gray-200 dark:border-slate-800 transition-colors">
              <div className="px-5 py-3 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Terminal className="w-4 h-4 text-indigo-500 dark:text-indigo-400" />
                  <span className="font-['JetBrains_Mono',_monospace] text-[13px] font-semibold text-zinc-800 dark:text-slate-200">
                    main.tf
                  </span>
                  {/* Metadata Badges */}
                  <div className="hidden sm:flex items-center gap-2 ml-3">
                    <span className="px-2 py-0.5 rounded text-[10px] font-medium text-zinc-500 dark:text-slate-400 bg-zinc-100 dark:bg-slate-800 border border-zinc-200/80 dark:border-slate-700/80 transition-colors">
                      Terraform
                    </span>
                    <span className="px-2 py-0.5 rounded text-[10px] font-medium text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-100/50 dark:border-emerald-800/30 transition-colors">
                      High (92%)
                    </span>
                    <span className="font-mono text-[10px] text-zinc-400 dark:text-slate-500 transition-colors">
                      a1f3c9d
                    </span>
                  </div>
                </div>

                {/* Right Actions */}
                <div className="flex items-center gap-1.5">
                  <div className="hidden sm:flex items-center mr-2 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-indigo-50 dark:bg-indigo-950/30 text-indigo-600 dark:text-indigo-400 border border-indigo-100/50 dark:border-indigo-800/30 gap-1.5 transition-colors">
                    <Zap className="w-3 h-3 text-indigo-500 dark:text-indigo-400" />
                    AI Snapshot
                  </div>
                  <button className="p-1.5 rounded-md text-zinc-400 hover:text-zinc-700 hover:bg-zinc-100 dark:hover:text-slate-200 dark:hover:bg-slate-800 transition-colors" title="Copy code">
                    <Copy className="w-3.5 h-3.5" />
                  </button>
                  <button className="p-1.5 rounded-md text-zinc-400 hover:text-zinc-700 hover:bg-zinc-100 dark:hover:text-slate-200 dark:hover:bg-slate-800 transition-colors" title="Download">
                    <Download className="w-3.5 h-3.5" />
                  </button>
                  <button className="p-1.5 rounded-md text-zinc-400 hover:text-zinc-700 hover:bg-zinc-100 dark:hover:text-slate-200 dark:hover:bg-slate-800 transition-colors" title="Fullscreen">
                    <Maximize2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* Infrastructure Impact Strip */}
              <div className="px-5 h-10 bg-white/50 dark:bg-[#010308]/30 flex items-center border-t border-gray-100 dark:border-slate-800/50 transition-colors">
                <span className="text-[11px] font-medium text-zinc-400 dark:text-slate-500 mr-4 tracking-wide uppercase">Impact Summary</span>
                <div className="flex items-center gap-4 font-['JetBrains_Mono',_monospace] text-[11px] font-semibold">
                  <span className="text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5"><span className="text-[14px] leading-none">+</span> 1 Lambda</span>
                  <span className="text-amber-500 dark:text-amber-400 flex items-center gap-1.5"><span className="text-[14px] leading-none">~</span> 1 IAM Role</span>
                  <span className="text-rose-500 dark:text-rose-400 flex items-center gap-1.5 text-opacity-70 dark:text-opacity-70 font-medium"><span className="text-[14px] leading-none">-</span> 0 Removed</span>
                </div>
              </div>
            </div>

            {/* Code Viewer — scrollable within pane */}
            <div className="flex-1 overflow-y-auto bg-[#f8f9fa] dark:bg-[#0a0c10] relative z-10 custom-scrollbar transition-colors">
              <pre className="text-[12.5px] leading-[1.55] py-4 font-['JetBrains_Mono',_monospace]">
                {terraformCode.split('\n').map((line, index) => {
                  const lineNumber = index + 1;
                  const isAddedLine = line.includes('memory_size') || line.includes('timeout') || line.includes('cors_configuration');
                  const isModifiedLine = line.includes('role          = aws_iam_role.lambda_exec.arn');
                  const isComment = line.trim().startsWith('#');
                  const isAnnotation = line.includes('Velocis:');
                  const isResourceHeader = line.startsWith('resource ') || line.startsWith('provider ') || line.startsWith('terraform {');

                  let highlightedLine = <span className="text-zinc-800 dark:text-slate-300 transition-colors">{line || ' '}</span>;

                  if (isComment) {
                    highlightedLine = <span className="text-zinc-400 dark:text-slate-500 transition-colors italic">{line}</span>;
                  } else if (isAnnotation) {
                    highlightedLine = <span className="text-indigo-600 dark:text-indigo-400 font-medium transition-colors">{line}</span>;
                  } else {
                    const parts = line.split(/(\".*?\"|{|}|[A-Za-z0-9_]+|[=]+)/g);
                    highlightedLine = (
                      <span className={isResourceHeader ? 'font-semibold' : ''}>
                        {parts.map((part, i) => {
                          if (!part) return null;
                          if (part.startsWith('"') && part.endsWith('"')) {
                            return <span key={i} className="text-amber-600 dark:text-amber-300">{part}</span>;
                          } else if (['resource', 'provider', 'terraform', 'required_providers'].includes(part)) {
                            return <span key={i} className="text-pink-600 dark:text-pink-400">{part}</span>;
                          } else if (['aws_lambda_function', 'aws_apigatewayv2_api', 'aws_dynamodb_table', 'aws_iam_role', 'aws_sfn_state_machine'].includes(part)) {
                            return <span key={i} className="text-purple-600 dark:text-purple-400">{part}</span>;
                          } else if (['memory_size', 'timeout', 'filename', 'function_name', 'role', 'handler', 'runtime', 'environment', 'variables', 'name', 'protocol_type', 'cors_configuration', 'billing_mode', 'hash_key', 'range_key', 'attribute', 'type', 'ttl', 'attribute_name', 'enabled', 'tags', 'assume_role_policy', 'definition'].includes(part)) {
                            return <span key={i} className="text-sky-600 dark:text-sky-400">{part}</span>;
                          } else if (!isNaN(Number(part)) && part.trim() !== '') {
                            return <span key={i} className="text-orange-500 dark:text-orange-400">{part}</span>;
                          } else if (part === '=') {
                            return <span key={i} className="text-zinc-400 dark:text-slate-500">{part}</span>;
                          } else {
                            return <span key={i} className="text-zinc-800 dark:text-slate-200">{part}</span>;
                          }
                        })}
                      </span>
                    );
                  }

                  // Determine Gutter Symbol & Styling
                  let gutterSymbol = ' ';
                  let bgStyle = 'border-l-[3px] border-l-transparent';
                  let numBgStyle = '';
                  let codeBgStyle = '';
                  let numColor = 'text-zinc-400 dark:text-slate-600';

                  if (isAddedLine) {
                    gutterSymbol = '+';
                    bgStyle = 'border-l-[3px] border-l-emerald-500';
                    numBgStyle = 'bg-emerald-50/50 dark:bg-emerald-900/10 text-emerald-600 dark:text-emerald-500';
                    codeBgStyle = 'bg-emerald-50/70 dark:bg-emerald-900/20';
                  } else if (isModifiedLine) {
                    gutterSymbol = '~';
                    bgStyle = 'border-l-[3px] border-l-amber-500';
                    numBgStyle = 'bg-amber-50/50 dark:bg-amber-900/10 text-amber-600 dark:text-amber-500';
                    codeBgStyle = 'bg-amber-50/70 dark:bg-amber-900/20';
                  }

                  return (
                    <div
                      key={index}
                      className={`flex items-start hover:bg-black/[0.02] dark:hover:bg-white/[0.02] transition-colors ${bgStyle}`}
                    >
                      <div
                        className={`inline-flex w-12 text-right select-none flex-shrink-0 border-r border-zinc-200/80 dark:border-slate-800 text-[11px] font-mono transition-colors ${numBgStyle}`}
                      >
                        <span className="w-5 text-center font-bold">{gutterSymbol}</span>
                        <span className={`w-7 pr-2 ${numColor}`}>{lineNumber}</span>
                      </div>
                      <div className={`flex-1 break-all pl-4 ${codeBgStyle}`}>
                        {highlightedLine}
                      </div>
                    </div>
                  );
                })}
              </pre>
            </div>

            {/* "Why this infra?" Footer - Deterministic AI Reasoning */}
            <div className="flex-none bg-white dark:bg-[#010308]/50 border-t border-gray-200 dark:border-slate-800 transition-colors">
              <button
                onClick={() => setIsWhyInfraExpanded(!isWhyInfraExpanded)}
                className="w-full flex items-center justify-between p-5 text-left hover:bg-zinc-50 dark:hover:bg-slate-900/50 transition-colors"
              >
                <h4 className="text-[13px] font-semibold text-zinc-900 dark:text-slate-100 tracking-tight flex items-center gap-2">
                  <Shield className="w-3.5 h-3.5 text-zinc-400 dark:text-slate-500" />
                  Why this infrastructure was inferred
                </h4>
                <ChevronDown
                  className={`w-4 h-4 text-zinc-400 dark:text-slate-500 transition-transform duration-200 ${isWhyInfraExpanded ? 'rotate-180' : ''}`}
                />
              </button>

              {isWhyInfraExpanded && (
                <div className="px-5 pb-5 pt-0">
                  <ul className="space-y-2.5">
                    <li className="flex items-start gap-2 text-[12px] leading-relaxed text-zinc-600 dark:text-slate-400">
                      <div className="w-1 h-1 rounded-full bg-zinc-300 dark:bg-slate-600 mt-2 flex-shrink-0" />
                      <span><strong>New authenticated API detected:</strong> The application code now requires session verification, prompting the addition of an API Gateway and Lambda authorizer.</span>
                    </li>
                    <li className="flex items-start gap-2 text-[12px] leading-relaxed text-zinc-600 dark:text-slate-400">
                      <div className="w-1 h-1 rounded-full bg-zinc-300 dark:bg-slate-600 mt-2 flex-shrink-0" />
                      <span><strong>Persistent storage usage found:</strong> Session data reads/writes observed in backend logic; DynamoDB payload configured with PAY_PER_REQUEST for optimal baseline cost.</span>
                    </li>
                    <li className="flex items-start gap-2 text-[12px] leading-relaxed text-zinc-600 dark:text-slate-400">
                      <div className="w-1 h-1 rounded-full bg-zinc-300 dark:bg-slate-600 mt-2 flex-shrink-0" />
                      <span><strong>Least-privilege execution:</strong> Implicitly bound Lambda execution role limits access exclusively to the specified DynamoDB resources.</span>
                    </li>
                  </ul>
                </div>
              )}
            </div>
          </motion.div>

          {/* ── RIGHT PANE: Analytics & Cost (30%) ── */}
          <motion.div
            initial={{ opacity: 0, x: 12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4, delay: 0.05 }}
            className="w-[30%] h-full bg-gray-50 dark:bg-[#010308]/70 flex flex-col overflow-hidden transition-colors duration-300"
          >
            {/* Scrollable content wrapper */}
            <div className="flex-1 overflow-y-auto custom-scrollbar">
              {/* ─── Cost Section ─── */}
              <div className="p-6 pb-6 mb-0 border-b border-gray-200 dark:border-slate-800">
                {/* Cost header */}
                <div className="flex items-start justify-between mb-2">
                  <h3 className="text-base font-semibold text-zinc-900 dark:text-slate-100 tracking-tight transition-colors">
                    Projected Monthly Cost
                  </h3>
                  <div className="text-[11px] text-zinc-500 dark:text-slate-400 px-2 py-0.5 bg-white dark:bg-slate-800 rounded border border-gray-200 dark:border-slate-700 transition-colors">
                    ap-south-1
                  </div>
                </div>

                <p className="text-[11px] text-zinc-500 dark:text-slate-400 mb-5 transition-colors">
                  Based on current traffic assumptions and infrastructure changes
                </p>

                {/* Primary Cost */}
                <motion.div
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                  className="mb-3"
                >
                  <div className="text-4xl font-semibold tracking-tight text-emerald-500 dark:text-emerald-400 transition-colors flex items-baseline gap-1">
                    <span className="text-2xl font-medium">$</span>
                    {monthlyCost.toFixed(2)}
                    <span className="text-lg font-medium text-zinc-400 dark:text-slate-500 ml-1">/ mo</span>
                  </div>
                </motion.div>

                {/* Cost Trend */}
                <div className="flex items-center gap-2 mb-6 px-2.5 py-1.5 rounded-md bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-100 dark:border-emerald-800/30 w-fit transition-colors">
                  <TrendingDown className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                  <span className="text-[12px] font-semibold text-emerald-700 dark:text-emerald-300 transition-colors">
                    ↓ 12% vs previous deployment
                  </span>
                </div>

                {/* Divider between cost data and breakdown */}
                <div className="border-b border-gray-200 dark:border-slate-800 pb-6 mb-6">
                  <h4 className="text-[13px] font-semibold mb-3 text-zinc-900 dark:text-slate-100 transition-colors">
                    Cost Breakdown
                  </h4>

                  {/* Stacked Bar */}
                  <div className="h-5 rounded overflow-hidden flex gap-[1px] mb-4 shadow-inner">
                    {costBreakdown.map((item, index) => (
                      <div
                        key={index}
                        className="group relative transition-all hover:brightness-110 hover:scale-y-105 origin-bottom cursor-pointer"
                        style={{
                          width: `${item.percentage}%`,
                          backgroundColor: item.color
                        }}
                      >
                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-3 px-3 py-2 rounded-md opacity-0 group-hover:opacity-100 transition-all pointer-events-none whitespace-nowrap bg-zinc-900 dark:bg-slate-100 shadow-xl z-50 transform group-hover:-translate-y-1">
                          <div className="text-[10px] font-bold text-zinc-400 dark:text-slate-500 uppercase tracking-widest mb-0.5">{item.service}</div>
                          <div className="text-sm font-semibold text-white dark:text-zinc-900">\${item.cost.toFixed(2)}</div>
                          <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-zinc-900 dark:border-t-slate-100" />
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Legend */}
                  <div className="space-y-2.5">
                    {costBreakdown.map((item, index) => (
                      <div key={index} className="flex items-center justify-between text-[13px] group/item">
                        <div className="flex items-center gap-2.5">
                          <div
                            className="w-2 h-2 rounded-full group-hover/item:scale-125 transition-transform"
                            style={{ backgroundColor: item.color }}
                          />
                          <span className="text-zinc-600 dark:text-slate-400 font-medium transition-colors">{item.service}</span>
                        </div>
                        <span className="font-semibold text-zinc-900 dark:text-slate-200 transition-colors">
                          \${item.cost.toFixed(2)}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* ─── Insights Section ─── */}
              <div className="p-6 border-b border-gray-200 dark:border-slate-800 space-y-3">
                <h4 className="text-[11px] font-bold uppercase tracking-widest text-zinc-400 dark:text-slate-500 mb-4">Insights</h4>

                {/* Scale-to-Zero Insight */}
                <div className="p-3.5 bg-white dark:bg-slate-900/50 border-l-[3px] border-l-emerald-500 border border-gray-200 dark:border-slate-800 rounded-md transition-colors">
                  <div className="flex items-start gap-2.5">
                    <Zap className="w-4 h-4 mt-0.5 flex-shrink-0 text-emerald-500 dark:text-emerald-400 transition-colors" />
                    <div>
                      <h4 className="text-[12px] font-semibold mb-0.5 text-zinc-900 dark:text-slate-100 transition-colors tracking-tight">
                        Serverless Efficiency
                      </h4>
                      <p className="text-[11px] leading-relaxed text-zinc-500 dark:text-slate-400 transition-colors font-medium">
                        No idle compute detected. Estimated baseline cost remains near zero during inactivity.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Cost Risk Alert */}
                {environment === 'production' && (
                  <div className="p-3.5 bg-white dark:bg-slate-900/50 border-l-[3px] border-l-amber-500 border border-gray-200 dark:border-slate-800 rounded-md transition-colors">
                    <div className="flex items-start gap-2.5">
                      <DollarSign className="w-4 h-4 mt-0.5 flex-shrink-0 text-amber-500 dark:text-amber-400 transition-colors" />
                      <div>
                        <h4 className="text-[12px] font-semibold mb-0.5 text-zinc-900 dark:text-slate-100 transition-colors tracking-tight">
                          Cost Optimization Tip
                        </h4>
                        <p className="text-[11px] leading-relaxed text-zinc-500 dark:text-slate-400 transition-colors font-medium">
                          Provisioned concurrency may increase monthly cost by ~22%. Consider on-demand for lower traffic.
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* ─── Change Impact Section ─── */}
              <div className="p-6 border-b border-gray-200 dark:border-slate-800">
                <h4 className="text-[11px] font-bold uppercase tracking-widest text-zinc-400 dark:text-slate-500 mb-4">Change Impact</h4>

                <div className="grid grid-cols-1 gap-3">
                  {/* Resources Added */}
                  <div className="flex items-center gap-3 p-3 bg-white dark:bg-slate-900/50 border border-gray-200 dark:border-slate-800 rounded-md transition-colors group">
                    <div className="w-9 h-9 rounded-md flex items-center justify-center bg-blue-50 dark:bg-blue-900/30 border border-blue-100 dark:border-blue-800/50 transition-colors flex-shrink-0">
                      <Server className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-[11px] font-medium text-zinc-500 dark:text-slate-400 transition-colors">Resources Added</div>
                      <div className="text-xl font-bold text-zinc-900 dark:text-slate-100 tracking-tight transition-colors leading-tight">3</div>
                    </div>
                  </div>

                  {/* Resources Modified */}
                  <div className="flex items-center gap-3 p-3 bg-white dark:bg-slate-900/50 border border-gray-200 dark:border-slate-800 rounded-md transition-colors group">
                    <div className="w-9 h-9 rounded-md flex items-center justify-center bg-amber-50 dark:bg-amber-900/30 border border-amber-100 dark:border-amber-800/50 transition-colors flex-shrink-0">
                      <Activity className="w-4 h-4 text-amber-500 dark:text-amber-400" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-[11px] font-medium text-zinc-500 dark:text-slate-400 transition-colors">Resources Modified</div>
                      <div className="text-xl font-bold text-zinc-900 dark:text-slate-100 tracking-tight transition-colors leading-tight">1</div>
                    </div>
                  </div>

                  {/* Security Posture */}
                  <div className="flex items-center gap-3 p-3 bg-white dark:bg-slate-900/50 border border-gray-200 dark:border-slate-800 rounded-md transition-colors group">
                    <div className="w-9 h-9 rounded-md flex items-center justify-center bg-emerald-50 dark:bg-emerald-900/30 border border-emerald-100 dark:border-emerald-800/50 transition-colors flex-shrink-0">
                      <Shield className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-[11px] font-medium text-zinc-500 dark:text-slate-400 transition-colors">Security Posture</div>
                      <div className="text-[12px] font-semibold text-emerald-600 dark:text-emerald-400 transition-colors flex items-center gap-1.5 mt-0.5">
                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                        No regressions
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* ─── Confidence Checks Section ─── */}
              <div className="p-6">
                <h4 className="text-[11px] font-bold uppercase tracking-widest text-zinc-400 dark:text-slate-500 mb-4">Confidence Checks</h4>
                <div className="space-y-3">
                  <div className="flex items-center gap-3 text-zinc-600 dark:text-slate-300 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors cursor-default">
                    <Lock className="w-3.5 h-3.5 shrink-0" />
                    <span className="text-[12px] font-medium leading-tight">Least-privilege IAM generated</span>
                  </div>
                  <div className="flex items-center gap-3 text-zinc-600 dark:text-slate-300 hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors cursor-default">
                    <Database className="w-3.5 h-3.5 shrink-0" />
                    <span className="text-[12px] font-medium leading-tight">No public S3 buckets detected</span>
                  </div>
                  <div className="flex items-center gap-3 text-zinc-600 dark:text-slate-300 hover:text-amber-600 dark:hover:text-amber-400 transition-colors cursor-default">
                    <Zap className="w-3.5 h-3.5 shrink-0" />
                    <span className="text-[12px] font-medium leading-tight">Serverless optimized</span>
                  </div>
                  <div className="flex items-center gap-3 text-zinc-600 dark:text-slate-300 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors cursor-default">
                    <RotateCcw className="w-3.5 h-3.5 shrink-0" />
                    <span className="text-[12px] font-medium leading-tight">Rollback ready</span>
                  </div>
                </div>
              </div>

            </div>{/* end scrollable content wrapper */}
          </motion.div>
        </div>

        {/* ── Bottom Status Bar ── */}
        <div className="flex-none z-50 w-full border-t border-gray-200 dark:border-slate-800/80 bg-white dark:bg-slate-900/60 transition-colors">
          <div className="w-full px-5 h-[28px] flex items-center justify-between text-[11px]">
            <span className="text-zinc-500 dark:text-slate-500 font-medium">© Velocis Core</span>
            <div className="flex items-center gap-5">
              <span className="text-zinc-400 dark:text-slate-500 font-medium hidden sm:inline">Documentation</span>
              <span className="text-zinc-400 dark:text-slate-500 font-medium hidden sm:inline">Support</span>
              <span className="text-emerald-600 dark:text-emerald-400 font-semibold flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shadow-[0_0_6px_rgba(16,185,129,0.5)]" />
                All Systems Operational
              </span>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
