"use client";

import { useState } from 'react';
import { motion } from 'motion/react';
import { ChevronDown, Download, RefreshCw, Shield, Lock, Zap, RotateCcw, DollarSign, TrendingDown, Server, Database, Activity, CloudCog } from 'lucide-react';
import { useNavigate, useParams } from 'react-router';

const terraformCode = `# Generated by Velocis IaC Predictor
# Source: latest commit on main branch
# Region: ap-south-1

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "ap-south-1"
}

# Lambda Function - Authentication Service
resource "aws_lambda_function" "auth_service" {
  filename      = "auth_service.zip"
  function_name = "auth-service-prod"
  role          = aws_iam_role.lambda_exec.arn
  handler       = "index.handler"
  runtime       = "nodejs20.x"
  
  memory_size = 256
  timeout     = 30
  
  environment {
    variables = {
      NODE_ENV = "production"
      DB_HOST  = aws_db_instance.main.endpoint
    }
  }
  
  # Velocis: New Lambda increases cold start surface
  tags = {
    ManagedBy = "Velocis"
    Service   = "Authentication"
  }
}

# API Gateway
resource "aws_apigatewayv2_api" "main" {
  name          = "velocis-api-prod"
  protocol_type = "HTTP"
  
  cors_configuration {
    allow_origins = ["*"]
    allow_methods = ["GET", "POST", "PUT", "DELETE"]
  }
}

# DynamoDB Table
resource "aws_dynamodb_table" "sessions" {
  name           = "user-sessions-prod"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "userId"
  range_key      = "sessionId"
  
  attribute {
    name = "userId"
    type = "S"
  }
  
  attribute {
    name = "sessionId"
    type = "S"
  }
  
  ttl {
    attribute_name = "expiresAt"
    enabled        = true
  }
  
  tags = {
    ManagedBy = "Velocis"
  }
}

# IAM Role for Lambda
resource "aws_iam_role" "lambda_exec" {
  name = "lambda-execution-role"
  
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

# Step Functions State Machine
resource "aws_sfn_state_machine" "workflow" {
  name     = "auth-workflow-prod"
  role_arn = aws_iam_role.step_functions_exec.arn
  
  definition = jsonencode({
    Comment = "Authentication workflow"
    StartAt = "ValidateUser"
    States = {
      ValidateUser = {
        Type = "Task"
        Resource = aws_lambda_function.auth_service.arn
        End = true
      }
    }
  })
}`;

export function InfrastructurePage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const [environment, setEnvironment] = useState<'production' | 'staging' | 'preview'>('production');
  const [monthlyCost, setMonthlyCost] = useState(18.42);
  
  const repoName = id === 'infrazero' ? 'InfraZero' : 
                   id === 'immersa' ? 'Immersa' : 
                   id === 'velocis-core' ? 'velocis-core' :
                   id === 'ai-observatory' ? 'ai-observatory' :
                   id === 'distributed-lab' ? 'distributed-lab' :
                   'test-sandbox';

  const costBreakdown = [
    { service: 'Lambda', cost: 8.50, percentage: 46, color: '#3b82f6' },
    { service: 'API Gateway', cost: 4.20, percentage: 23, color: '#8b5cf6' },
    { service: 'DynamoDB', cost: 3.40, percentage: 18, color: '#10b981' },
    { service: 'Step Functions', cost: 1.82, percentage: 10, color: '#f59e0b' },
    { service: 'Misc', cost: 0.50, percentage: 3, color: '#6b7280' }
  ];

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--bg-soft)' }}>
      {/* Infrastructure Top Bar */}
      <div 
        className="sticky top-0 z-50 border-b bg-white"
        style={{ borderColor: 'var(--border-subtle)' }}
      >
        <div className="max-w-[1280px] mx-auto px-6 h-[60px] flex items-center justify-between">
          {/* Left - Breadcrumb */}
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <div 
                className="w-7 h-7 rounded-lg flex items-center justify-center"
                style={{ backgroundColor: 'var(--cta-primary)' }}
              >
                <span className="text-white font-bold text-sm">V</span>
              </div>
              <span className="font-bold text-white hidden sm:block">Velocis</span>
            </div>
            
            <div className="flex items-center gap-2 text-sm" style={{ color: 'var(--text-secondary)' }}>
              <button 
                onClick={() => navigate('/dashboard')}
                className="hover:opacity-70 transition-opacity"
              >
                Dashboard
              </button>
              <span>/</span>
              <button 
                onClick={() => navigate(`/repo/${id}`)}
                className="hover:opacity-70 transition-opacity"
              >
                {repoName}
              </button>
              <span>/</span>
              <span className="text-black font-medium">Infrastructure</span>
            </div>
          </div>

          {/* Center - Environment Selector */}
          <div 
            className="hidden md:flex items-center rounded-lg p-1"
            style={{ backgroundColor: 'var(--bg-soft)' }}
          >
            {(['production', 'staging', 'preview'] as const).map((env) => (
              <button
                key={env}
                onClick={() => setEnvironment(env)}
                className="px-4 py-1.5 rounded-md text-sm font-medium transition-all capitalize"
                style={{
                  backgroundColor: environment === env ? '#ffffff' : 'transparent',
                  color: environment === env ? 'var(--text-primary)' : 'var(--text-secondary)',
                  boxShadow: environment === env ? '0 1px 2px rgba(0,0,0,0.05)' : 'none'
                }}
              >
                {env}
              </button>
            ))}
          </div>

          {/* Right - Actions */}
          <div className="flex items-center gap-3">
            <button 
              className="p-2 rounded-lg hover:bg-gray-50 transition-colors"
              title="Refresh"
            >
              <RefreshCw className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
            </button>
            <button 
              className="p-2 rounded-lg hover:bg-gray-50 transition-colors"
              title="Export IaC"
            >
              <Download className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
            </button>
            <div 
              className="w-8 h-8 rounded-full flex items-center justify-center"
              style={{ backgroundColor: 'var(--accent-purple-soft)' }}
            >
              <span className="text-sm font-semibold" style={{ color: 'var(--accent-purple)' }}>
                R
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Context Strip */}
      <div 
        className="px-6 py-3 flex items-center justify-between border-b"
        style={{ 
          backgroundColor: 'var(--bg-soft)',
          borderColor: 'var(--border-subtle)'
        }}
      >
        <div>
          <div className="font-semibold text-sm" style={{ color: 'var(--text-primary)' }}>
            IaC Predictor active
          </div>
          <div className="text-xs" style={{ color: 'var(--text-secondary)' }}>
            Infrastructure changes generated from latest commit
          </div>
        </div>
        
        <div className="flex items-center gap-3">
          <div 
            className="px-3 py-1 rounded-full text-xs"
            style={{ 
              backgroundColor: 'var(--accent-purple-soft)',
              color: 'var(--accent-purple)'
            }}
          >
            Generated by Amazon Q
          </div>
          <div className="text-xs" style={{ color: 'var(--text-secondary)' }}>
            Last updated 2 min ago
          </div>
          <div className="text-xs" style={{ color: 'var(--text-secondary)' }}>
            Region: ap-south-1
          </div>
        </div>
      </div>

      {/* Main Two-Panel Workspace */}
      <div className="max-w-[1280px] mx-auto p-6">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-8">
          {/* IaC Code Panel */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="lg:col-span-7 bg-white rounded-[18px] border overflow-hidden"
            style={{ borderColor: 'var(--border-subtle)' }}
          >
            {/* Panel Header */}
            <div 
              className="px-6 py-4 border-b flex items-center justify-between"
              style={{ borderColor: 'var(--border-subtle)' }}
            >
              <h3 className="font-semibold" style={{ color: 'var(--text-primary)' }}>
                Generated Infrastructure
              </h3>
              <div 
                className="px-3 py-1 rounded-md text-xs font-medium"
                style={{ 
                  backgroundColor: 'var(--accent-purple-soft)',
                  color: 'var(--accent-purple)'
                }}
              >
                AI Generated
              </div>
            </div>

            {/* Code Viewer */}
            <div className="overflow-auto max-h-[600px]">
              <pre className="text-xs leading-relaxed p-6" style={{ fontFamily: 'Menlo, Monaco, "Courier New", monospace' }}>
                {terraformCode.split('\n').map((line, index) => {
                  const lineNumber = index + 1;
                  const isAddedLine = line.includes('memory_size') || line.includes('timeout') || line.includes('cors_configuration');
                  const isComment = line.trim().startsWith('#');
                  const isAnnotation = line.includes('Velocis:');
                  
                  return (
                    <div 
                      key={index}
                      className={`flex items-start ${isAddedLine ? 'bg-green-50' : ''}`}
                    >
                      {/* Line number */}
                      <span 
                        className="inline-block w-10 text-right mr-4 select-none flex-shrink-0"
                        style={{ color: '#9ca3af' }}
                      >
                        {lineNumber}
                      </span>
                      
                      {/* Code line */}
                      <span 
                        className="flex-1"
                        style={{ 
                          color: isComment ? '#6b7280' : isAnnotation ? 'var(--accent-purple)' : '#1f2937'
                        }}
                      >
                        {line}
                      </span>
                    </div>
                  );
                })}
              </pre>
            </div>
          </motion.div>

          {/* Cost Intelligence Panel */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="lg:col-span-5 bg-white rounded-[18px] border p-6"
            style={{ borderColor: 'var(--border-subtle)' }}
          >
            <h3 className="text-lg font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>
              Projected AWS Cost
            </h3>
            <p className="text-xs mb-6" style={{ color: 'var(--text-secondary)' }}>
              Based on current traffic assumptions
            </p>

            {/* Primary Cost Widget */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="mb-3"
            >
              <div 
                className="text-5xl font-bold tracking-tight"
                style={{ color: '#22c55e' }}
              >
                ${monthlyCost.toFixed(2)}
                <span className="text-2xl font-normal" style={{ color: 'var(--text-secondary)' }}> / month</span>
              </div>
            </motion.div>

            {/* Cost Trend */}
            <div className="flex items-center gap-2 mb-8">
              <TrendingDown className="w-4 h-4" style={{ color: '#22c55e' }} />
              <span className="text-sm font-medium" style={{ color: '#22c55e' }}>
                ↓ 12% vs previous deployment
              </span>
            </div>

            {/* Cost Breakdown Chart */}
            <div className="mb-8">
              <h4 className="text-sm font-semibold mb-4" style={{ color: 'var(--text-primary)' }}>
                Cost Breakdown
              </h4>
              
              {/* Stacked Bar */}
              <div className="h-8 rounded-lg overflow-hidden flex mb-4">
                {costBreakdown.map((item, index) => (
                  <div
                    key={index}
                    className="group relative transition-all hover:opacity-80 cursor-pointer"
                    style={{ 
                      width: `${item.percentage}%`,
                      backgroundColor: item.color
                    }}
                  >
                    {/* Tooltip */}
                    <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-1.5 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap"
                         style={{ backgroundColor: 'rgba(0,0,0,0.9)' }}>
                      <div className="text-xs text-white font-medium">{item.service}</div>
                      <div className="text-xs text-gray-300">${item.cost.toFixed(2)}</div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Legend */}
              <div className="space-y-2">
                {costBreakdown.map((item, index) => (
                  <div key={index} className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <div 
                        className="w-3 h-3 rounded"
                        style={{ backgroundColor: item.color }}
                      />
                      <span style={{ color: 'var(--text-secondary)' }}>{item.service}</span>
                    </div>
                    <span className="font-medium" style={{ color: 'var(--text-primary)' }}>
                      ${item.cost.toFixed(2)}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Scale-to-Zero Insight */}
            <div 
              className="rounded-lg p-4 mb-6"
              style={{ 
                backgroundColor: '#f0fdf4',
                border: '1px solid #86efac'
              }}
            >
              <div className="flex items-start gap-3">
                <Zap className="w-5 h-5 mt-0.5 flex-shrink-0" style={{ color: '#22c55e' }} />
                <div>
                  <h4 className="text-sm font-semibold mb-2" style={{ color: '#166534' }}>
                    Serverless Efficiency Insight
                  </h4>
                  <p className="text-xs leading-relaxed" style={{ color: '#15803d' }}>
                    No idle compute detected. Estimated baseline cost remains near zero during inactivity windows.
                  </p>
                </div>
              </div>
            </div>

            {/* Cost Risk Alert (conditional) */}
            {environment === 'production' && (
              <div 
                className="rounded-lg p-4"
                style={{ 
                  backgroundColor: '#fef3c7',
                  border: '1px solid #fcd34d'
                }}
              >
                <div className="flex items-start gap-3">
                  <DollarSign className="w-5 h-5 mt-0.5 flex-shrink-0" style={{ color: '#d97706' }} />
                  <div>
                    <h4 className="text-sm font-semibold mb-2" style={{ color: '#92400e' }}>
                      Cost Optimization Tip
                    </h4>
                    <p className="text-xs leading-relaxed" style={{ color: '#b45309' }}>
                      Provisioned concurrency may increase monthly cost by ~22%. Consider on-demand for lower traffic periods.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </motion.div>
        </div>

        {/* Change Impact Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="mb-8"
        >
          <h3 className="text-lg font-semibold mb-4" style={{ color: 'var(--text-primary)' }}>
            Infrastructure Impact Summary
          </h3>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div 
              className="bg-white rounded-[14px] border p-5"
              style={{ borderColor: 'var(--border-subtle)' }}
            >
              <div className="flex items-center gap-3 mb-3">
                <div 
                  className="w-10 h-10 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: '#dbeafe' }}
                >
                  <Server className="w-5 h-5" style={{ color: '#3b82f6' }} />
                </div>
                <div>
                  <div className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>3</div>
                  <div className="text-xs" style={{ color: 'var(--text-secondary)' }}>Resources Added</div>
                </div>
              </div>
            </div>

            <div 
              className="bg-white rounded-[14px] border p-5"
              style={{ borderColor: 'var(--border-subtle)' }}
            >
              <div className="flex items-center gap-3 mb-3">
                <div 
                  className="w-10 h-10 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: '#fef3c7' }}
                >
                  <Activity className="w-5 h-5" style={{ color: '#f59e0b' }} />
                </div>
                <div>
                  <div className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>1</div>
                  <div className="text-xs" style={{ color: 'var(--text-secondary)' }}>Resources Modified</div>
                </div>
              </div>
            </div>

            <div 
              className="bg-white rounded-[14px] border p-5"
              style={{ borderColor: 'var(--border-subtle)' }}
            >
              <div className="flex items-center gap-3 mb-3">
                <div 
                  className="w-10 h-10 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: '#dcfce7' }}
                >
                  <Shield className="w-5 h-5" style={{ color: '#22c55e' }} />
                </div>
                <div>
                  <div className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Security Posture</div>
                  <div className="text-xs" style={{ color: '#22c55e' }}>No regressions</div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Bottom Confidence Strip */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="rounded-[14px] p-6"
          style={{ backgroundColor: 'var(--bg-soft)' }}
        >
          <div className="flex flex-wrap items-center justify-center gap-8">
            <div className="flex items-center gap-2">
              <Lock className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
              <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                Least-privilege IAM generated
              </span>
            </div>
            <div className="flex items-center gap-2">
              <Database className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
              <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                No public S3 buckets detected
              </span>
            </div>
            <div className="flex items-center gap-2">
              <Zap className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
              <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                Serverless optimized
              </span>
            </div>
            <div className="flex items-center gap-2">
              <RotateCcw className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
              <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                Rollback ready
              </span>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Footer */}
      <footer className="mt-8 py-8 px-6 border-t" style={{ borderColor: 'var(--border-subtle)' }}>
        <div className="max-w-[1280px] mx-auto flex items-center justify-between">
          <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>
            © Velocis
          </span>
          <div className="flex items-center gap-6">
            <a href="#" className="text-sm hover:opacity-70 transition-opacity" style={{ color: 'var(--text-secondary)' }}>
              Docs
            </a>
            <a href="#" className="text-sm hover:opacity-70 transition-opacity" style={{ color: 'var(--text-secondary)' }}>
              Security
            </a>
            <a href="#" className="text-sm hover:opacity-70 transition-opacity" style={{ color: 'var(--text-secondary)' }}>
              Status
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
